In [41]:
import numpy as np

In [43]:
array = np.arange(10,21)

In [44]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
array[5]

15

In [46]:
array[5:10]

array([15, 16, 17, 18, 19])

In [60]:
array[:5]

array([100, 100, 100, 100, 100])

In [61]:
array[5:] #takes beyond index

array([15, 16, 17, 18, 19, 20])

In [66]:
array = np.arange(10,21)

In [67]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [68]:
array_copy = array.copy()

In [69]:
array_copy

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [70]:
array_copy[:5] = 90

In [71]:
array_copy

array([90, 90, 90, 90, 90, 15, 16, 17, 18, 19, 20])

In [73]:
array2d = np.array([[5,6,7],[8,9,10],[11,12,13]])

In [74]:
array2d

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [75]:
array2d[1,2]

10

In [77]:
array2d[:2,1:]

array([[ 6,  7],
       [ 9, 10]])

In [78]:
array2 = np.arange(100,200,10)

In [79]:
array2

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [80]:
bool_arr = array2>150

In [81]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [83]:
array2[bool_arr]

array([160, 170, 180, 190])

In [85]:
array2[array2<150]

array([100, 110, 120, 130, 140])

In [84]:
array2

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [ ]:
a